wandb_version: 1

image_size:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 32
data_class:
  desc: null
  value: cat
train_steps:
  desc: null
  value: 10000
time_steps:
  desc: null
  value: 50
unet_dim:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.001
save_and_sample_every:
  desc: null
  value: 1000
fid:
  desc: null
  value: false
dataloader_workers:
  desc: null
  value: 16
unet_dim_mults:
  desc: null
  value:
  - 1
  - 2
  - 4
  - 8
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.11.9
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728251469
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
